import type { CourseDetail, SourceCourse, StandardDetail } from "./types";
export type BulkManifest = {
  id: string;
  createdAt: string;
  engine: string;
  model: string;
  modelRevision: string;
  courses: number;
  eligible: number;
  computed: number;
  missing: number;
  excluded: number;
  standards: number;
  levels: number;
  criteria: number;
  pairs: number;
  direct: number;
  blocked: number;
  inputs: number;
  sourceIndexHash: string;
  vectorHash: string;
  snapshotDates: string[];
  method: string;
  scope: string;
};
export type BulkCourseRow = {
  id: string;
  run_id: string;
  course_id: string;
  code: string;
  title: string;
  department: string;
  category: string;
  level: string;
  status: string;
  basis: string;
  score: number | null;
  standard_title: string;
  pair_count: number;
  result_path: string;
  result_hash: string;
};
export type BulkTarget = {
  id: string;
  text: string;
  kind: string;
  locator: string;
};
export type BulkMatch = {
  targetId: string;
  uoc: string;
  uocTitle: string;
  eoc: string;
  eocTitle: string;
  criterion: string;
  locator: string;
  similarity: number;
  cosine: number;
  critical: boolean;
  negation: boolean;
  theoryGap: boolean;
};
export type BulkPair = {
  id: string;
  standardId: number;
  title: string;
  level: string;
  sourceUrl: string;
  standardPath: string;
  standardHash: string;
  basis: string;
  referenceNote: string;
  mismatch: boolean;
  score: number;
  retrievalScore: number;
  criteria: number;
  matches: BulkMatch[];
};
export type BulkDetail = {
  runId: string;
  courseId: string;
  summary: SourceCourse;
  course: CourseDetail | null;
  provenance: Record<string, unknown>;
  courseHash: string;
  targets: BulkTarget[];
  pairs: BulkPair[];
  status: string;
  note: string;
};
export type BulkStandardFile = {
  standard: StandardDetail;
  provenance: Record<string, unknown>;
};
